AWSTemplateFormatVersion: '2010-09-09'
Description: Artifacts for Lambda functions

Parameters:
  LogBucketName:
    Type: String
    AllowedPattern: '[a-z][a-z0-9]*'
    Description: Name of Amazon S3 bucket for log [a-z][a-z0-9]*

  ElasticsearchDomainName:
    Type: String
    AllowedPattern: '[a-z][a-z0-9]*'
    Description: Name of Elasticsearch domain for log [a-z][a-z0-9]*

  ElasticsearchIndexName:
    Type: String
    AllowedPattern: '[a-z][a-z0-9]*'
    Description: Name of Elasticsearch index from Kinesis Firehose [a-z][a-z0-9]*
    
  FirehoseName:
    Type: String
    AllowedPattern: '[a-z][a-z0-9]*'
    Description: DeliveryStream for ES and S3 [a-z][a-z0-9]*

  MasterPassword:
    Type: String
    Description: Master password for Elastic admin user
    MinLength: 12

Resources:

  LambdaSourceBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: aws-nlp-data-pipeline-lambda

  ElasticsearchDomain: 
    Type: AWS::Elasticsearch::Domain
    Properties:
      DomainName: !Sub "${ElasticsearchDomainName}"
      ElasticsearchVersion: "7.9"
      ElasticsearchClusterConfig: 
        InstanceCount: 1
        InstanceType: "t3.small.elasticsearch"
      EBSOptions: 
        EBSEnabled: true
        Iops: 0
        VolumeSize: 10
        VolumeType: "gp2"
      SnapshotOptions: 
        AutomatedSnapshotStartHour: 0
      DomainEndpointOptions:
        EnforceHTTPS: true
      EncryptionAtRestOptions:
        Enabled: true
      NodeToNodeEncryptionOptions:
        Enabled: true
      AdvancedSecurityOptions:
        Enabled: true
        InternalUserDatabaseEnabled: true
        MasterUserOptions:
          MasterUserName: "admin"
          MasterUserPassword: !Sub "${MasterPassword}"
      AccessPolicies: 
        Version: "2012-10-17"
        Statement: 
          - Effect: "Allow"
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: "es:*"
            Resource: !Sub "arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/${ElasticsearchDomainName}/*"
          - Effect: "Allow"
            Principal:
              AWS: "*"
            Action: "es:ESHttp*"
            Resource: !Sub "arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/${ElasticsearchDomainName}/*"

  LogBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref "LogBucketName"
      AccessControl: Private


Outputs:

  LambdaSourceBucket:
    Description: Name of S3 bucket where Lambda artifacts are stored
    Value: !Ref LambdaSourceBucket