AWSTemplateFormatVersion: '2010-09-09'
Description: Artifacts for Lambda functions

Resources:

  LambdaSourceBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: aws-nlp-data-pipeline-lambda

Outputs:

  LambdaSourceBucket:
    Description: Name of S3 bucket where Lambda artifacts are stored
    Value: !Ref LambdaSourceBucket