name: deploy

on:
  push:
    branches: [ master ]

jobs:

  cloudformation-deploy:

    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    
    runs-on: ubuntu-latest
    
    steps:

      - name: checkout
        uses: actions/checkout@v2
  
      - name: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: deploy-core-stack
        id: deploy-core-stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1.0.3
        env:
          LOG_BUCKET_NAME: numsds498awsnlp
          ELASTICSEARCH_DOMAIN_NAME: esdomainname
          ELASTICSEARCH_INDEX_NAME: test
          FIREHOSE_NAME: firehosetest
        with:
          name: CoreStack
          template: cfn/core-stack.yml
          capabilities: 'CAPABILITY_NAMED_IAM'
          no-fail-on-empty-changeset: 1
          parameter-overrides: "LogBucketName=${{ env.LOG_BUCKET_NAME }},ElasticsearchDomainName=${{ env.ELASTICSEARCH_DOMAIN_NAME }},ElasticsearchIndexName=${{ env.ELASTICSEARCH_INDEX_NAME }},FirehoseName=${{ env.FIREHOSE_NAME }}"

      - name: zip-ingest-lambda
        run: zip -r ingest.zip src/ingest
      
      - name: zip-comprehend-lambda
        run: zip -r comprehend.zip src/ingest

      - name: push-zip
        env:
          BUCKET: ${{ steps.deploy-core-stack.outputs.LambdaSourceBucket }}
        run: aws s3 cp ingest.zip "s3://$BUCKET/ingest.zip"

      - name: push-comprehend-zip
        env:
          BUCKET: ${{ steps.deploy-core-stack.outputs.LambdaSourceBucket }}
        run: aws s3 cp comprehend.zip "s3://$BUCKET/comprehend.zip"

      - name: deploy-ingest-stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1.0.3
        env:
          LOG_BUCKET_NAME: numsds498awsnlp
          ELASTICSEARCH_DOMAIN_NAME: esdomainname
          ELASTICSEARCH_INDEX_NAME: test
          FIREHOSE_NAME: firehosetest
        with:
          name: IngestStack
          template: cfn/ingest-stack.yml
          capabilities: 'CAPABILITY_NAMED_IAM'
          no-fail-on-empty-changeset: 1
          parameter-overrides: "S3SourceBucket=${{ steps.deploy-core-stack.outputs.LambdaSourceBucket }},LogBucketName=${{ env.LOG_BUCKET_NAME }},ElasticsearchDomainName=${{ env.ELASTICSEARCH_DOMAIN_NAME }},ElasticsearchIndexName=${{ env.ELASTICSEARCH_INDEX_NAME }},FirehoseName=${{ env.FIREHOSE_NAME }}"
      
      - name: update-ingest-code
        run: aws lambda update-function-code IngestStack-handler --function-name --s3-bucket ${{ steps.deploy-core-stack.outputs.LambdaSourceBucket }} --s3-key ingest.zip

      - name: update-comprehend-code
        run: aws lambda update-function-code IngestStack-comprehend-handler --function-name --s3-bucket ${{ steps.deploy-core-stack.outputs.LambdaSourceBucket }} --s3-key comprehend.zip
