name: deploy

on:
  push:
    branches: [ master ]

jobs:
  
  cloudformation-linter:
    
    runs-on: ubuntu-latest

    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: cfn-lint
        uses: ScottBrenner/cfn-lint-action@master
        with:
          args: "cfn/*.yml"

  cloudformation-deploy:

    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    
    runs-on: ubuntu-latest
    
    needs: cloudformation-linter
    
    steps:

      - name: Checkout
        uses: actions/checkout@v2
  
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Deploy Lambda Artifact Bucket
        uses: aws-actions/aws-cloudformation-github-deploy@v1.0.3
        with:
          name: LambdaArtifacts
          template: cfn/lambda-artifacts.yml
          capabilities: 'CAPABILITY_NAMED_IAM'
          no-fail-on-empty-changeset: 1

      - name: Zip Ingest Lambda
        run: zip -r ingest.zip src/ingest

      - run: echo s3://${{steps.Deploy_Lambda_Artifact_Bucket.outputs.LambdaSourceBucket}}/ingest.zip

      - name: Push Zip
        run: aws s3 cp ingest.zip s3://${{steps.Deploy_Lambda_Artifact_Bucket.outputs.LambdaSourceBucket}}/ingest.zip

      - name: Deploy Stream and Storage
        uses: aws-actions/aws-cloudformation-github-deploy@v1.0.3
        env:
          LOG_BUCKET_NAME: numsds498awsnlp
          ELASTICSEARCH_DOMAIN_NAME: esdomainname
          ELASTICSEARCH_INDEX_NAME: test
          FIREHOSE_NAME: firehosetest
        with:
          name: TestStack
          template: storage-stack.yml
          capabilities: 'CAPABILITY_NAMED_IAM'
          parameter-overrides: "LogBucketName=${{ env.LOG_BUCKET_NAME }},ElasticsearchDomainName=${{ env.ELASTICSEARCH_DOMAIN_NAME }},ElasticsearchIndexName=${{ env.ELASTICSEARCH_INDEX_NAME }},FirehoseName=${{ env.FIREHOSE_NAME }}"