name: deploy

on:
  push:
    branches: [ master ]

jobs:
  
  cloudformation-linter:
    
    runs-on: ubuntu-latest

    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: cfn-lint
        uses: ScottBrenner/cfn-lint-action@master
        with:
          args: "stack.yml"

  cloudformation-deploy:
    
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    
    runs-on: ubuntu-latest
    
    needs: cloudformation-linter
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Deploy Stream and Storage
        uses: aws-actions/aws-cloudformation-github-deploy@v1.0.3
        env:
          LOG_BUCKET_NAME: numsds498awsnlp
          ELASTICSEARCH_DOMAIN_NAME: esdomainname
          ELASTICSEARCH_INDEX_NAME: test
          FIREHOSE_NAME: firehosetest
        with:
          name: TestStack
          template: stack.yml
          capabilities: 'CAPABILITY_NAMED_IAM'
          parameter-overrides: "LogBucketName=${{ env.LOG_BUCKET_NAME }},ElasticsearchDomainName=${{ env.ELASTICSEARCH_DOMAIN_NAME }},ElasticsearchIndexName=${{ env.ELASTICSEARCH_INDEX_NAME }},FirehoseName=${{ env.FIREHOSE_NAME }}"
